"""Change Products and Sizes table structure

Revision ID: 105359e13b22
Revises: d34cfbb1925d
Create Date: 2024-08-11 04:09:44.027473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '105359e13b22'
down_revision: Union[str, None] = 'd34cfbb1925d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('products_id_size_fkey', 'products', type_='foreignkey')
    op.drop_column('products', 'id_size')
    op.add_column('sizes', sa.Column('id_product', sa.UUID(), nullable=False))
    op.drop_column('sizes', 'product_category')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sizes', sa.Column('product_category', postgresql.ENUM('PIZZA', 'PASTA', 'DRINKS', 'DESSERT', 'LOOONGER', 'SNACKS', 'OTHER', name='categoryenum'), autoincrement=False, nullable=False))
    op.drop_column('sizes', 'id_product')
    op.add_column('products', sa.Column('id_size', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('products_id_size_fkey', 'products', 'sizes', ['id_size'], ['id'])
    # ### end Alembic commands ###
