"""Change Products, Sizes tables

Revision ID: 392b58a500ef
Revises: e977c9cac319
Create Date: 2024-08-16 04:22:40.951733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '392b58a500ef'
down_revision: Union[str, None] = 'e977c9cac319'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredient_product', sa.Column('is_added', sa.Boolean(), nullable=True))
    op.alter_column('products', 'price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.drop_column('products', 'base_price')
    op.add_column('sizes', sa.Column('price', sa.DECIMAL(precision=10, scale=2), nullable=False))
    op.drop_column('sizes', 'multiplier')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sizes', sa.Column('multiplier', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.drop_column('sizes', 'price')
    op.add_column('products', sa.Column('base_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.alter_column('products', 'price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.drop_column('ingredient_product', 'is_added')
    # ### end Alembic commands ###
