"""Added carts and products

Revision ID: 4b2314bd1e83
Revises: 716319bef325
Create Date: 2024-08-08 04:40:27.333134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b2314bd1e83'
down_revision: Union[str, None] = '716319bef325'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_user', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'ORDERED', 'ABANDONED', name='cartstatusenum'), nullable=False),
    sa.ForeignKeyConstraint(['id_user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id_size', sa.UUID(), nullable=True),
    sa.Column('category', sa.Enum('PIZZA', 'PASTA', 'DRINKS', 'DESSERT', 'LOOONGER', 'SNACKS', 'OTHER', name='categoryenum'), nullable=False),
    sa.Column('base_price', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('price', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['id_size'], ['sizes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    op.drop_table('carts')
    # ### end Alembic commands ###
