"""Added cart items, orders and ingredient-product

Revision ID: 6cab9713fa6c
Revises: 4b2314bd1e83
Create Date: 2024-08-08 04:42:56.570512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cab9713fa6c'
down_revision: Union[str, None] = '4b2314bd1e83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_product', sa.UUID(), nullable=True),
    sa.Column('id_cart', sa.UUID(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('total_price', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['id_cart'], ['carts.id'], ),
    sa.ForeignKeyConstraint(['id_product'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingredient_product',
    sa.Column('id_product', sa.UUID(), nullable=False),
    sa.Column('id_ingredient', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('is_removable', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_ingredient'], ['ingredients.id'], ),
    sa.ForeignKeyConstraint(['id_product'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id_product', 'id_ingredient')
    )
    op.create_table('orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_user', sa.UUID(), nullable=True),
    sa.Column('id_cart', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='orderstatusenum'), nullable=False),
    sa.Column('total_price', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['id_cart'], ['carts.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    op.drop_table('ingredient_product')
    op.drop_table('cart_items')
    # ### end Alembic commands ###
