"""Add product_category field to Sizes table

Revision ID: d34cfbb1925d
Revises: 0fd92b58fd91
Create Date: 2024-08-10 04:31:19.809408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd34cfbb1925d'
down_revision: Union[str, None] = '0fd92b58fd91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sizes', sa.Column('product_category', sa.Enum('PIZZA', 'PASTA', 'DRINKS', 'DESSERT', 'LOOONGER', 'SNACKS', 'OTHER', name='categoryenum'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sizes', 'product_category')
    # ### end Alembic commands ###
