"""empty message

Revision ID: e977c9cac319
Revises: 105359e13b22
Create Date: 2024-08-11 04:36:10.262378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e977c9cac319'
down_revision: Union[str, None] = '105359e13b22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sizes', 'id_product',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_foreign_key(None, 'sizes', 'products', ['id_product'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sizes', type_='foreignkey')
    op.alter_column('sizes', 'id_product',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
